<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\20260209134020_InitialCreateDataModels.cs" />
    <Compile Remove="Migrations\20260209134020_InitialCreateDataModels.Designer.cs" />
    <Compile Remove="Migrations\20260212104020_AddCollectionProperties.cs" />
    <Compile Remove="Migrations\20260212104020_AddCollectionProperties.Designer.cs" />
    <Compile Remove="Migrations\20260212114234_AddedDescription.cs" />
    <Compile Remove="Migrations\20260212114234_AddedDescription.Designer.cs" />
    <Compile Remove="Migrations\20260215125318_AddedUserId.cs" />
    <Compile Remove="Migrations\20260215125318_AddedUserId.Designer.cs" />
    <Compile Remove="Migrations\20260215130240_MakeUserIdRequired.cs" />
    <Compile Remove="Migrations\20260215130240_MakeUserIdRequired.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyCraftHobbyApp.Data.Models\MyCraftHobbyApp.Data.Models.csproj" />
  </ItemGroup>

</Project>
